//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace astronomy5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AstroEntities : DbContext
    {
        public AstroEntities()
            : base("name=AstroEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Lidaparati> Lidaparati { get; set; }
        public virtual DbSet<Misijas> Misijas { get; set; }
        public virtual DbSet<Pavadoni> Pavadoni { get; set; }
        public virtual DbSet<Planetas> Planetas { get; set; }
        public virtual DbSet<RefTips> RefTips { get; set; }
    }
}
