//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace astronomy5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefTips
    {
        public RefTips()
        {
            this.Misijas = new HashSet<Misijas>();
        }
    
        public int RefTipsID { get; set; }
        public string Veids { get; set; }
    
        public virtual ICollection<Misijas> Misijas { get; set; }
    }
}
